<a href="https://colab.research.google.com/github/austinvanderlyn/School-Files/blob/master/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [3]:
type(a)

numpy.ndarray

In [4]:
a[:2]

array([1., 4.])

In [5]:
a[3]

8.0

In [6]:
a[0]

1.0

In [7]:
a

array([1., 4., 5., 8.])

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a.shape

(2, 3)

In [9]:
a[0, 0]

1.0

In [10]:
a[0, 1]

2.0

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a[1,:]

array([4., 5., 6.])

In [12]:
a[:,2]

array([3., 6.])

In [13]:
a[-1:,-2:]

array([[5., 6.]])

In [14]:
a.shape

(2, 3)

In [15]:
a.dtype

dtype('float64')

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
len(a)

2

In [17]:
2 in a

True

In [18]:
0 in a

False

In [19]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
a = a.reshape((5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [21]:
a.shape

(5, 2)

In [22]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()
a[0] = 0

In [23]:
a

array([0., 2., 3.])

In [24]:
b

array([0., 2., 3.])

In [25]:
c

array([1., 2., 3.])

In [26]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [27]:
a.fill(0)
a

array([0., 0., 0.])

In [28]:
a = np.array([1, 2], float)
b = np.array([3, 4, 5, 6], float)
c = np.array([7, 8, 9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
np.concatenate((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [30]:
np.concatenate((a, b), axis = 0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [31]:
np.concatenate((a, b), axis = 1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [32]:
a = np.array([1, 2, 3], float)
a.shape

(3,)

In [33]:
a[:, np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [34]:
a[:, np.newaxis].shape

(3, 1)

In [35]:
b[np.newaxis,:]

array([[[5., 6.],
        [7., 8.]]])

In [36]:
b[np.newaxis,:].shape

(1, 2, 2)

In [37]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[2, 0], [1, 3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [38]:
a = np.array([[1,2], [3,4], [5,6]], float)
b = np.array([-1,3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [39]:
b

array([-1.,  3.])

In [40]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [41]:
a = np.array([1, 4, 5], int)
for x in a:
  print(x)

1
4
5


In [42]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [43]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a:
  print(x * y)

2.0
12.0
30.0


In [44]:
a = np.array ([[0, 2], [3, -1], [3, 5]], float)
a.mean(axis = 0)

array([2., 2.])

In [45]:
a.mean(axis=1)

array([1., 1., 4.])

In [46]:
a.max(axis=0)

array([3., 5.])

In [47]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [48]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

In [49]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [50]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([1., 4., 5., 7.])

In [51]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([1., 4.])

In [52]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b

array([ True, False, False])

In [53]:
c = a > b

In [54]:
c

array([ True, False, False])

In [55]:
a = np.array([1, 3, 0], float)
a > 2

array([False,  True, False])

In [56]:
c = np.array([True, False, False], bool)
any(c)

True

In [57]:
all(c)

False

In [58]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [59]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [60]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [61]:
a = np.array([[0, 1], [3,0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

In [62]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [63]:
np.isnan(a)

array([False,  True, False])

In [64]:
np.isfinite(a)

array([ True, False, False])

In [65]:
a = np.array([[6, 4], [5, 9 ]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [66]:
a[a >= 6]

array([6., 9.])

In [67]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [68]:
a = np.array([2, 4, 6, 8], float)
a [[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

In [69]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
a

array([[0., 1.],
       [2., 3.]])

In [70]:
np.dot(b, a)

array([ 6., 11.])

In [71]:
np.dot(a, b)

array([ 3., 13.])

In [72]:
np.dot(a, c)

array([[ 4.,  0.],
       [14.,  2.]])

In [73]:
np.dot(c, a)

array([[2., 4.],
       [0., 4.]])

In [74]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [75]:
np.linalg.det(a)

-48.00000000000003

In [76]:
vals, vecs = np.linalg.eig(a)

In [77]:
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [78]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [79]:
b = np.linalg.inv(a)

In [80]:
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [81]:
np.dot(a, b)

array([[1.00000000e+00, 5.55111512e-17, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.38777878e-17, 1.00000000e+00]])

In [82]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)
np.outer(a, b)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [83]:
np.inner(a, b)

10.0

In [84]:
np.cross(a, b)

array([ 4., -1., -6.])

In [85]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a)

3.0

In [87]:
a = np.array([[1, 2, 1, 3],
             [5, 3, 1, 8]],
             float)
c = np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [88]:
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

In [89]:
np.random.rand(5)

array([0.50925479, 0.97907724, 0.11899022, 0.10853239, 0.80590575])

In [90]:
np.random.rand(2, 3)

array([[0.08610466, 0.01161586, 0.97193981],
       [0.56415616, 0.44113715, 0.90174248]])

In [92]:
np.random.rand(6).reshape((2, 3))

array([[0.63192438, 0.29114863, 0.82987496],
       [0.53031516, 0.84610649, 0.01973954]])

In [93]:
np.random.random()

0.4948787076098502

In [94]:
np.random.randint(5, 10)

7